// LOGIN TYPES
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

// LOGOUT TYPES
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// SIGNUP TYPES
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

// SHOPPING CART
export const GET_CART = 'GET_CART'
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS'
export const ADD_BOOK_REQUEST = 'ADD_BOOK_REQUEST'
export const ADD_BOOK_FAILED = 'ADD_BOOK_FAILED'
export const UPDATE_BOOK_REQUEST = 'UPDATE_BOOK_REQUEST'
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS'
export const UPDATE_BOOK_FAILED = 'UPDATE_BOOK_FAILED'
export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST'
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS'
export const DELETE_BOOK_FAILED = 'DELETE_BOOK_FAILED'

